# Generated by Django 4.2.1 on 2023-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
