# Generated by Django 4.2.1 on 2023-05-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0002_laboratory_delete_labs'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='Chairnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='numpcnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='statuspc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
