# Generated by Django 4.2.1 on 2023-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0004_alter_laboratory_building_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(max_length=90, null=True)),
                ('lab_id', models.IntegerField(default=0)),
                ('pc_id', models.IntegerField(default=0)),
            ],
        ),
    ]
