# Generated by Django 4.2.1 on 2023-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0006_alter_laboratory_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lab_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
