# Generated by Django 4.2.1 on 2023-05-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0007_alter_report_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='lab_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
