# Generated by Django 4.2.1 on 2023-05-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0008_alter_laboratory_lab_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='Chairnum',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='building_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='capacity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='floor_number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='numpcnum',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
