# Generated by Django 4.2.1 on 2023-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0009_alter_laboratory_chairnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratory',
            name='Chairnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='building_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='floor_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='lab_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='numpcnum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab_id',
            field=models.IntegerField(default=0),
        ),
    ]
