# Generated by Django 4.2.1 on 2023-05-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labfly', '0012_alter_report_lab_id_alter_report_pc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lab_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='pc_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.CharField(default=0, max_length=90),
            preserve_default=False,
        ),
    ]
